### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by dliessi** [frescobaldi/frescobaldi#1237]
Reported by @marnen on 15 May 2019 (unofficial Frescobaldi 3.0.0 app bundle) and confirmed today (official Frescobaldi 3.1 app bundle) on 10.14 Mojave (see #986):

> The Sessions menu doesn't work well: every time I click on it, I get an error that says something about "too many values to unpack". Once I dismiss the error, the menu doesn't show the sessions I have defined, but otherwise functions as expected.

> When the app opens, I get the following error:
> ```
> Traceback (most recent call last):
>   File "/private/var/folders/yq/n3t_19_13897mtqk4w1lx7jc0000gq/T/AppTranslocation/EF3958AC-8D5F-4D76-9E97-CDEA5D3B62D9/d/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/sessions/menu.py", line 100, in populate
> ValueError: too many values to unpack (expected 2)
> ```
> Clicking "cancel" either has no effect or brings up the error alert again; ditto the close box. Clicking "email bug report" opens Mail.app and then returns to the error. The error alert is modal; all non-system menu items are disabled, and clicking on the application window just gets an error beep. Even the Quit menu item is disabled, and so I have to force-quit Fresco.

> Hmm, when I copied to a location other than the DMG, I still got the error but was eventually able to cancel my way out of it. But then it reappeared every time I switched focus back to the application.

I cannot reproduce the issue.

@wbsoft any ideas?

**Comment by dliessi** [comment]
@marnen: Would you please try renaming or moving Frescobaldi's preferences file (`~/Library/Preferences/org.frescobaldi.frescobaldi.plist`) and see if the Session menu still has the problem?

You can then delete the newly created preferences file and move the previous one back to its original location.

**Comment by uliska** [comment]
This may be related to "old" sessions stored in the preferences not being compatible with the changed implementation. But I'm not sure, I recall having such errors when working on hierarchical sessions and switching branches.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by dliessi** [comment]
> This may be related to "old" sessions stored in the preferences not being compatible with the changed implementation.

If that's indeed the case, then resetting the preferences (by deleting the file mentioned above) should solve the issue.

@uliska: do you think that exporting the sessions, deleting the preferences and importing the sessions again would work?
Ideally, users should not need to rebuild all sessions from scratch.

**Comment by uliska** [comment]
*If* that's the issue I think exporting/importing should work because I don't think snything was changed there.

Unfortunately I can't have a look at the code ATM. 
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by marnen** [comment]
@dliessi:

> Would you please try renaming or moving Frescobaldi's preferences file (`~/Library/Preferences/org.frescobaldi.frescobaldi.plist`) 

Sure, I was going to suggest doing something like that. Let me see what I can figure out.

**Comment by marnen** [comment]
I'm sorry to say that that didn't make a difference. With the old prefs file moved out of the way, in Fresco 3.1 I still get the same error as soon as I click on the Session menu.

**Comment by wbsoft** [comment]
I'll have a look into it shortly.
